name: Build and run checks for the admin portal
on:
  pull_request:
    branches:
      - development
      - master
  push:
    branches:
      - development
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: admin-portal
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run prttier check
        run: npm run prettier-check
      - name: Build the app
        run: CI=false npm run build # treating warning as warnings until wiring up with the backend 
